baseURL="https://www.2dsteve.com"
languageCode = "en-us"
title = "2D Steve"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-188083095-1"
disqusShortname = "2dsteve"

[params]
author = "Stephen Adams"
description = "It's About The Journey"
profilePicture = "/img/StephEmote.png"
mainSections = ["post"]
title = "Stephen Adams"
copyright = "2004-2023"
darkMode = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "How I Work"
  weight = 300
  identifier = "how-i-work"
  url = "/how-i-work/"

  [[menu.main]]
  name = "Life Rules"
  weight = 400
  identifier = "life-rules"
  url = "/life-rules/"

[[params.socialIcons]]
icon = "fab fa-mastodon"
name = "Mastodon"
url = "https://www.fosstodon.org/@2DSteve"

[[params.socialIcons]]
icon = "fab fa-github"
name = "Github"
url = "https://www.github.com/stevehnh"

[[params.socialIcons]]
icon = "fab fa-discord"
name = "Discord"
url = "https://www.2dorks.net/discord"

[[params.socialIcons]]
icon = "fab fa-twitch"
name = "Twitch"
url = "https://www.twitch.tv/2dorkstv"

[[params.socialIcons]]
icon = "fab fa-tiktok"
name = "TikTok"
url = "https://www.tiktok.com/@stevehnh"

