baseURL="https://www.2dsteve.com"
languageCode = "en-us"
title = "Stephen Adams"
theme = "hugo-ficurinia"
paginate = 5
summarylength = 70 
#googleAnalytics = "UA-188083095-1"
#disqusShortname = "2dsteve"

[params]
  author = "Stephen Adams"
  description = "It's About The Journey"
  copyright = "2004-2022"
  
  posts = "posts"
  showPostsLink = true
  imageInArticlePreview = true
  enableShareOnFediverse = true
  
  # cactus comments
  cactusCommentsSiteName = "2dsteve.com"
  cactusCommentsServerName = "cactus.chat"
  cactusCommentsHomeserver = "https://matrix.cactus.chat:8448"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    lineNumbersInTable =false
    tabWidth = 4
    style = "dracula"
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 1

[menu]

  [[menu.main]]
  name = "How I Work"
  weight = 300
  identifier = "how-i-work"
  url = "/how-i-work/"

  [[menu.icons]]
  identifier = "github"
  name = "Github"
  url = "https://www.github.com/SteveHNH"
  weight = 20

  [[menu.icons]]
  identifier = "mastodon"
  name = "Mastadon"
  url = "https://fosstodon.org/@2DSteve"
  weight = 10

  [[menu.icons]]
  identifier = "discord"
  name = "Discord"
  url = "https://2dorks.net/discord"
  weight = 30

  [[menu.icons]]
  identifier = "youtube"
  name = "YouTube"
  url = "https://2dorks.net/youtube"
  weight = 40

